version: 2
jobs:
  build:
    working_directory: ~/superrecord
    docker:
      - image: fpco/stack-build:lts-8.20
    steps:
      - checkout
      - restore_cache:
          key: stack-cache
      - run:
          name: stack setup
          command: 'stack setup'
      - run:
          name: stack install dependencies
          command: 'stack build --test --bench --only-dependencies'
      - save_cache:
          key: stack-cache
          paths:
            - ~/.stack
            - ~/superrecord/.stack-work
      - run:
          name: stack build
          command: 'stack build --fast --pedantic'
      - run:
          name: stack test
          command: 'stack test --fast'
      - run:
          name: build benchmarks
          command: 'stack build --fast --bench --no-run-benchmarks'
  build-ghc82:
    working_directory: ~/superrecord2
    docker:
      - image: fpco/stack-build:lts-8.20
    steps:
      - checkout
      - restore_cache:
          key: stack-cache-ghc82
      - run:
          name: stack upgrade
          command: 'stack upgrade'
      - run:
          name: stack setup
          command: 'stack --resolver nightly setup'
      - run:
          name: stack install dependencies
          command: 'stack --resolver nightly build --test --only-dependencies'
      - save_cache:
          key: stack-cache-ghc82
          paths:
            - ~/.stack
            - ~/superrecord2/.stack-work
      - run:
          name: stack build
          command: 'stack --resolver nightly build --fast --pedantic'
      - run:
          name: stack test
          command: 'stack --resolver nightly test --fast'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build-ghc82
